name: tbot

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
      
      - name: Install data.table package
        run: Rscript -e 'install.packages("data.table", dependencies = TRUE)'
      
      - name: Install ggplot2 package
        run: Rscript -e 'install.packages("ggplot2", dependencies = TRUE)'
      
      - name: Install scales package
        run: Rscript -e 'install.packages("scales", dependencies = TRUE)'
      
      - name: Install ggpubr package
        run: Rscript -e 'install.packages("ggpubr", dependencies = TRUE)'
      
      - name: Install grid package
        run: Rscript -e 'install.packages("grid", dependencies = TRUE)'
      
      - name: Install RColorBrewer package
        run: Rscript -e 'install.packages("RColorBrewer", dependencies = TRUE)'
      
      - name: Install ggdark package
        run: Rscript -e 'install.packages("ggdark", dependencies = TRUE)'
      
      - name: Install ggpattern package
        run: Rscript -e 'install.packages("ggpattern", dependencies = TRUE)'
      
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      
      - name: Create and post tweet
        run: Rscript send-tweet.R
      
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
